### ISSUE TITLE
Dataset acquisition application

### ISSUE THREAD

**Issue by lgqlp** [ManfredGonzalez/multispectral-pineapple-detection#1]
How do I download the dataset? Thank you very much.

**Comment by ManfredGonzalez** [comment]
> How do I download the dataset? Thank you very much.

Hi there. So sorry, the official pineapple dataset is not available. The farm who was providing us the dataset decided not to make public their images.  I have finished this research and now I don't have access to any of their images. Although, the pipeline was designed to be used with any image set produced with the DJI UAV Phantom 4 Multi-spectral so, you can try to using the pipeline with your own dataset. So sorry for my poor response.
